name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to EC2
        run: |
          ssh-keyscan -H 18.234.24.166 >> ~/.ssh/known_hosts
          scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} . ubuntu@ec2-18-234-24-166.compute-1.amazonaws.co:/home/ubuntu/
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ec2-18-234-24-166.compute-1.amazonaws.com 'bash -s' < deploy_script.sh
      
